/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyecto_poo_;

import java.awt.event.KeyEvent;
import java.util.ArrayList;
import static proyecto_poo_.Datos_juegos.cbxInjustice2;
import static proyecto_poo_.Datos_juegos.cbxRedDeadRedemption2;
import static proyecto_poo_.Datos_juegos.cbxRiseTombRaider;

/**
 *
 * @author Pavilion
 */
public class Datos_del_Comprador extends javax.swing.JFrame {

    /**
     * Creates new form Datos_del_Comprador
     */
    ArrayList<Videojuego> listaJuegos = new ArrayList<>();

    public Datos_del_Comprador() {
        initComponents();
    }
       
    Factura factura = new Factura();
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
   
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        lblNumFactura = new javax.swing.JLabel();
        lblNumeral = new javax.swing.JLabel();
        lblNumCedula = new javax.swing.JLabel();
        txtCédula = new javax.swing.JTextField();
        lblNombre = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        lblApellidp = new javax.swing.JLabel();
        txtApellido = new javax.swing.JTextField();
        lblFecha = new javax.swing.JLabel();
        cmbDia = new javax.swing.JComboBox<>();
        cmbMes = new javax.swing.JComboBox<>();
        cmbAño = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        lblTipoConsola = new javax.swing.JLabel();
        lblComplemento = new javax.swing.JLabel();
        lblValorAPagar = new javax.swing.JLabel();
        btnGuardar = new javax.swing.JButton();
        txtConsolaAdquirida = new javax.swing.JTextField();
        txtPrecioConsola = new javax.swing.JTextField();
        cbmTipoComplemento = new javax.swing.JComboBox<>();
        txtValorAPagar = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txaResultados = new javax.swing.JTextArea();
        lblTexto = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel4.setBackground(new java.awt.Color(255, 204, 204));

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Cabecera de factura"));

        lblNumFactura.setText("Número de Factura:");

        lblNumeral.setText("######");

        lblNumCedula.setText("Número de Cédula:");

        lblNombre.setText("Nombre:");

        lblApellidp.setText("Apellido:");

        txtApellido.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtApellidoKeyPressed(evt);
            }
        });

        lblFecha.setText("Fecha:");

        cmbDia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27. 28. 29", "30", "31" }));
        cmbDia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbDiaActionPerformed(evt);
            }
        });

        cmbMes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12" }));
        cmbMes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbMesActionPerformed(evt);
            }
        });

        cmbAño.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1990", "1991", "1992", "1993", "1994", "1995", "1996", "1997", "1998", "1999", "2000", "2001", "2002", "2003", "2004", "2005", "2006", "2007", "2008", "2009", "2010", "2011", "2012", "2013", "2014", "2015", "2016", "2017", "2018", "2019", "2020" }));
        cmbAño.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbAñoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(lblNumFactura)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblNumeral)
                .addGap(148, 148, 148))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNumCedula)
                    .addComponent(lblNombre)
                    .addComponent(lblApellidp)
                    .addComponent(lblFecha))
                .addGap(74, 74, 74)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCédula, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(cmbDia, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmbMes, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmbAño, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(86, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNumFactura)
                    .addComponent(lblNumeral, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNumCedula)
                    .addComponent(txtCédula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombre)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblApellidp)
                    .addComponent(txtApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblFecha)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cmbDia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cmbMes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cmbAño, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(50, Short.MAX_VALUE))
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Detalle de factura"));

        lblTipoConsola.setText("Consola:");

        lblComplemento.setText("Complemento adquirido:");

        lblValorAPagar.setText("Valor a pagar:");

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        cbmTipoComplemento.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Control", "Audífonos", "Fundas Protectoras" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblComplemento)
                    .addComponent(lblValorAPagar))
                .addGap(52, 52, 52)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtValorAPagar, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbmTipoComplemento, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 84, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnGuardar)
                .addGap(141, 141, 141))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(lblTipoConsola)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtConsolaAdquirida, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtPrecioConsola, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(95, 95, 95))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTipoConsola)
                    .addComponent(txtConsolaAdquirida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPrecioConsola, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblComplemento)
                    .addComponent(cbmTipoComplemento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblValorAPagar)
                    .addComponent(txtValorAPagar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnGuardar))
        );

        jLabel2.setText("DATOS DEL COMPRADOR");

        txaResultados.setEditable(false);
        txaResultados.setColumns(20);
        txaResultados.setRows(5);
        jScrollPane1.setViewportView(txaResultados);

        lblTexto.setText("FACTURA DE COMPRA ");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/ArrayGames.png"))); // NOI18N

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(68, 68, 68)
                        .addComponent(lblTexto)))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 7, Short.MAX_VALUE))))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblTexto)
                        .addComponent(jLabel2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmbDiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbDiaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbDiaActionPerformed

    private void cmbMesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbMesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbMesActionPerformed

    private void cmbAñoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbAñoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbAñoActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        // TODO add your handling code here:
        String dia;
        String mes;
        String año;
        String tipoConsola;
        String complemento;

        factura.setNumCedula(txtCédula.getText());
        factura.setNombre(txtNombre.getText());
        factura.setApellido(txtApellido.getText());
        dia = (String) cmbDia.getSelectedItem();
        mes = (String) cmbDia.getSelectedItem();
        año = (String) cmbAño.getSelectedItem();
        factura.setFecha(dia + "/" + mes + "/" + año);
        String nombreConsola = txtConsolaAdquirida.getText();
        double precioConsola = Double.parseDouble(txtPrecioConsola.getText());
        Consola consolaAVender = new Consola(nombreConsola,precioConsola);
        factura.setConsola(consolaAVender);
        complemento = (String) cbmTipoComplemento.getSelectedItem();
        factura.setComplemento(complemento);
        factura.setListaJuegos(listaJuegos);
        factura.setValorAPagar(Double.parseDouble(txtValorAPagar.getText()));
        txaResultados.setText(factura.toString());
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void txtApellidoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtApellidoKeyPressed

        
// TODO add your handling code here:
if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
        String nombre = "";
        double precio = 0;
        String exclusividad = "";
        if (Datos_juegos.cbxAnimalCrossing.isSelected()) {
            nombre = "Animal Crossing: New Horizons";
            precio = 55;
            exclusividad = "Si";
            Videojuego nuevoJuego = new VideojuegoNintendoSwitch(nombre, precio, exclusividad);
            if (nuevoJuego.esExclusivo()) {
                nuevoJuego.agregarDescuento();
            }
            listaJuegos.add(nuevoJuego);
        }
        if (Datos_juegos.cbxAssassinsCreedOdyssey.isSelected()) {
            nombre = "Assassins Creed Odyssey";
            precio = 24;
            exclusividad = "No";
            Videojuego nuevoJuego = new Videojuego(nombre, precio, exclusividad);
            if (nuevoJuego.esExclusivo()) {
                nuevoJuego.agregarDescuento();
            }
            listaJuegos.add(nuevoJuego);
        }
        
        if (Datos_juegos.cbxAssassinsCreedOrigins.isSelected()) {
            nombre = "Assassins Creed Origins";
            precio = 35;
            exclusividad = "No";
            Videojuego nuevoJuego = new Videojuego(nombre, precio, exclusividad);
            if (nuevoJuego.esExclusivo()) {
                nuevoJuego.agregarDescuento();
            }
            listaJuegos.add(nuevoJuego);
        }
        if (Datos_juegos.cbxAssassinsCreedUnity.isSelected()) {
            nombre = "Assassins Creed Unity";
            precio = 20;
            exclusividad = "No";
            Videojuego nuevoJuego = new Videojuego(nombre, precio, exclusividad);
            if (nuevoJuego.esExclusivo()) {
                nuevoJuego.agregarDescuento();
            }
            listaJuegos.add(nuevoJuego);
        }
        if (Datos_juegos.cbxBattlefield5.isSelected()) {
            nombre = "Battlefield V";
            precio = 27;
            exclusividad = "No";
            Videojuego nuevoJuego = new Videojuego(nombre, precio, exclusividad);
            if (nuevoJuego.esExclusivo()) {
                nuevoJuego.agregarDescuento();
            }
            listaJuegos.add(nuevoJuego);
        }
        if (Datos_juegos.cbxBioshockInfinite.isSelected()) {
            nombre = "Bioshock Infinite";
            precio = 10;
            exclusividad = "No";
            Videojuego nuevoJuego = new Videojuego(nombre, precio, exclusividad);
            if (nuevoJuego.esExclusivo()) {
                nuevoJuego.agregarDescuento();
            }
            listaJuegos.add(nuevoJuego);
        }
        if (Datos_juegos.cbxCodMW.isSelected()) {
            nombre = "Call of Duty: Modern Warfare";
            precio = 39;
            exclusividad = "No";
            Videojuego nuevoJuego = new Videojuego(nombre, precio, exclusividad);
            if (nuevoJuego.esExclusivo()) {
                nuevoJuego.agregarDescuento();
            }
            listaJuegos.add(nuevoJuego);
        }
        if (Datos_juegos.cbxDaysGone.isSelected()) {
            nombre = "Days Gone";
            precio = 33;
            exclusividad = "Si";
            Videojuego nuevoJuego = new VideojuegoPS4(nombre, precio, exclusividad);
            if (nuevoJuego.esExclusivo()) {
                nuevoJuego.agregarDescuento();
            }
            listaJuegos.add(nuevoJuego);
        }
        if (Datos_juegos.cbxDeadByDaylight.isSelected()) {
            nombre = "Dead by Daylight";
            precio = 20;
            exclusividad = "No";
            Videojuego nuevoJuego = new Videojuego(nombre, precio, exclusividad);
            if (nuevoJuego.esExclusivo()) {
                nuevoJuego.agregarDescuento();
            }
            listaJuegos.add(nuevoJuego);
        }
        if (Datos_juegos.cbxDragonBallFZ.isSelected()) {
            nombre = "Dragon Ball FighterZ";
            precio = 35;
            exclusividad = "No";
            Videojuego nuevoJuego = new Videojuego(nombre, precio, exclusividad);
            if (nuevoJuego.esExclusivo()) {
                nuevoJuego.agregarDescuento();
            }
            listaJuegos.add(nuevoJuego);
        }
        if (Datos_juegos.cbxDragonBallX2.isSelected()) {
            nombre = "Dragon Ball Xenoverse 2";
            precio = 25;
            exclusividad = "No";
            Videojuego nuevoJuego = new Videojuego(nombre, precio, exclusividad);
            if (nuevoJuego.esExclusivo()) {
                nuevoJuego.agregarDescuento();
            }
            listaJuegos.add(nuevoJuego);
        }
        if (Datos_juegos.cbxFallGuys.isSelected()) {
            nombre = "Fall Guys Ultimate Knockout";
            precio = 10;
            exclusividad = "No";
            Videojuego nuevoJuego = new Videojuego(nombre, precio, exclusividad);
            if (nuevoJuego.esExclusivo()) {
                nuevoJuego.agregarDescuento();
            }
            listaJuegos.add(nuevoJuego);
        }
        if (Datos_juegos.cbxFIFA20.isSelected()) {
            nombre = "FIFA 20";
            precio = 35;
            exclusividad = "No";
            Videojuego nuevoJuego = new Videojuego(nombre, precio, exclusividad);
            if (nuevoJuego.esExclusivo()) {
                nuevoJuego.agregarDescuento();
            }
            listaJuegos.add(nuevoJuego);
        }
        if (Datos_juegos.cbxForzaHorizon.isSelected()) {
            nombre = "Forza Horizon 4";
            precio = 75;
            exclusividad = "Si";
            Videojuego nuevoJuego = new VideojuegoXboxOne(nombre, precio, exclusividad);
            if (nuevoJuego.esExclusivo()) {
                nuevoJuego.agregarDescuento();
            }
            listaJuegos.add(nuevoJuego);
        }
        if (Datos_juegos.cbxForzaMotorsport.isSelected()) {
            nombre = "Forza Motorsport 7";
            precio = 25;
            exclusividad = "Si";
            Videojuego nuevoJuego = new VideojuegoXboxOne(nombre, precio, exclusividad);
            if (nuevoJuego.esExclusivo()) {
                nuevoJuego.agregarDescuento();
            }
            listaJuegos.add(nuevoJuego);
        }
        if (Datos_juegos.cbxFriday13.isSelected()) {
            nombre = "Friday the 13th: The Game";
            precio = 15;
            exclusividad = "No";
            Videojuego nuevoJuego = new Videojuego(nombre, precio, exclusividad);
            if (nuevoJuego.esExclusivo()) {
                nuevoJuego.agregarDescuento();
            }
            listaJuegos.add(nuevoJuego);
        }
        if (Datos_juegos.cbxGears5.isSelected()) {
            nombre = "Gears 5";
            precio = 28;
            exclusividad = "Si";
            Videojuego nuevoJuego = new VideojuegoXboxOne(nombre, precio, exclusividad);
            if (nuevoJuego.esExclusivo()) {
                nuevoJuego.agregarDescuento();
            }
            listaJuegos.add(nuevoJuego);
        }
        if (Datos_juegos.cbxGearsOfWar4.isSelected()) {
            nombre = "Gears of War 4";
            precio = 15;
            exclusividad = "Si";
            Videojuego nuevoJuego = new VideojuegoXboxOne(nombre, precio, exclusividad);
            if (nuevoJuego.esExclusivo()) {
                nuevoJuego.agregarDescuento();
            }
            listaJuegos.add(nuevoJuego);
        }
        if (Datos_juegos.cbxGodOfWar.isSelected()) {
            nombre = "God of War";
            precio = 20;
            exclusividad = "Si";
            Videojuego nuevoJuego = new VideojuegoPS4(nombre, precio, exclusividad);
            if (nuevoJuego.esExclusivo()) {
                nuevoJuego.agregarDescuento();
            }
            listaJuegos.add(nuevoJuego);
        }
        if (Datos_juegos.cbxGranTurismo.isSelected()) {
            nombre = "Gran Turismo Sport";
            precio = 15;
            exclusividad = "Si";
            Videojuego nuevoJuego = new VideojuegoPS4(nombre, precio, exclusividad);
            if (nuevoJuego.esExclusivo()) {
                nuevoJuego.agregarDescuento();
            }
            listaJuegos.add(nuevoJuego);
        }
        if (Datos_juegos.cbxHalo5.isSelected()) {
            nombre = "HALO 5: Guardians";
            precio = 20;
            exclusividad = "Si";
            Videojuego nuevoJuego = new VideojuegoXboxOne(nombre, precio, exclusividad);
            if (nuevoJuego.esExclusivo()) {
                nuevoJuego.agregarDescuento();
            }
            listaJuegos.add(nuevoJuego);
        }
        if (Datos_juegos.cbxHorizonZeroDawn.isSelected()) {
            nombre = "Horizon Zero Dawn";
            precio = 20;
            exclusividad = "Si";
            Videojuego nuevoJuego = new VideojuegoPS4(nombre, precio, exclusividad);
            if (nuevoJuego.esExclusivo()) {
                nuevoJuego.agregarDescuento();
            }
            listaJuegos.add(nuevoJuego);
        }
        if (Datos_juegos.cbxInfamousSS.isSelected()) {
            nombre = "Infamous Second Son";
            precio = 15;
            exclusividad = "Si";
            Videojuego nuevoJuego = new VideojuegoPS4(nombre, precio, exclusividad);
            if (nuevoJuego.esExclusivo()) {
                nuevoJuego.agregarDescuento();
            }
            listaJuegos.add(nuevoJuego);
        }
        if (Datos_juegos.cbxMarioKart8.isSelected()) {
            nombre = "Mario Kart 8 Deluxe";
            precio = 45;
            exclusividad = "Si";
            Videojuego nuevoJuego = new VideojuegoNintendoSwitch(nombre, precio, exclusividad);
            if (nuevoJuego.esExclusivo()) {
                nuevoJuego.agregarDescuento();
            }
            listaJuegos.add(nuevoJuego);
        }
        if (Datos_juegos.cbxMarvelAvengers.isSelected()) {
            nombre = "Marvel's Avengers";
            precio = 47;
            exclusividad = "No";
            Videojuego nuevoJuego = new Videojuego(nombre, precio, exclusividad);
            if (nuevoJuego.esExclusivo()) {
                nuevoJuego.agregarDescuento();
            }
            listaJuegos.add(nuevoJuego);
        }
        if (Datos_juegos.cbxMUA3.isSelected()) {
            nombre = "Marvel Ultimate Alliance 3: The Black Order";
            precio = 35;
            exclusividad = "Si";
            Videojuego nuevoJuego = new VideojuegoNintendoSwitch(nombre, precio, exclusividad);
            if (nuevoJuego.esExclusivo()) {
                nuevoJuego.agregarDescuento();
            }
            listaJuegos.add(nuevoJuego);
        }
        if (Datos_juegos.cbxSpiderMan.isSelected()) {
            nombre = "Marvel's Spider-Man";
            precio = 20;
            exclusividad = "Si";
            Videojuego nuevoJuego = new VideojuegoPS4(nombre, precio, exclusividad);
            if (nuevoJuego.esExclusivo()) {
                nuevoJuego.agregarDescuento();
            }
            listaJuegos.add(nuevoJuego);
        }
        if (Datos_juegos.cbxMinecraft.isSelected()) {
            nombre = "Minecraft";
            precio = 15;
            exclusividad = "No";
            Videojuego nuevoJuego = new Videojuego(nombre, precio, exclusividad);
            if (nuevoJuego.esExclusivo()) {
                nuevoJuego.agregarDescuento();
            }
            listaJuegos.add(nuevoJuego);
        }
        if (Datos_juegos.cbxMortalKombat11.isSelected()) {
            nombre = "Mortal Kombat 11";
            precio = 35;
            exclusividad = "No";
            Videojuego nuevoJuego = new Videojuego(nombre, precio, exclusividad);
            if (nuevoJuego.esExclusivo()) {
                nuevoJuego.agregarDescuento();
            }
            listaJuegos.add(nuevoJuego);
        }
        if (Datos_juegos.cbxNBA20.isSelected()) {
            nombre = "NBA 2K20";
            precio = 30;
            exclusividad = "No";
            Videojuego nuevoJuego = new Videojuego(nombre, precio, exclusividad);
            if (nuevoJuego.esExclusivo()) {
                nuevoJuego.agregarDescuento();
            }
            listaJuegos.add(nuevoJuego);
        }
        if (Datos_juegos.cbxNBA21.isSelected()) {
            nombre = "NBA 2K21";
            precio = 43;
            exclusividad = "No";
            Videojuego nuevoJuego = new Videojuego(nombre, precio, exclusividad);
            if (nuevoJuego.esExclusivo()) {
                nuevoJuego.agregarDescuento();
            }
            listaJuegos.add(nuevoJuego);
        }
        if (Datos_juegos.cbxOri.isSelected()) {
            nombre = "Ori and the Will of the Wisps";
            precio = 20;
            exclusividad = "Si";
            Videojuego nuevoJuego = new VideojuegoXboxOne(nombre, precio, exclusividad);
            if (nuevoJuego.esExclusivo()) {
                nuevoJuego.agregarDescuento();
            }
            listaJuegos.add(nuevoJuego);
        }
        if (Datos_juegos.cbxOverwatch.isSelected()) {
            nombre = "Overwatch";
            precio = 25;
            exclusividad = "No";
            Videojuego nuevoJuego = new Videojuego(nombre, precio, exclusividad);
            if (nuevoJuego.esExclusivo()) {
                nuevoJuego.agregarDescuento();
            }
            listaJuegos.add(nuevoJuego);
        }
        if (Datos_juegos.cbxPES2020.isSelected()) {
            nombre = "PES 2020";
            precio = 18;
            exclusividad = "No";
            Videojuego nuevoJuego = new Videojuego(nombre, precio, exclusividad);
            if (nuevoJuego.esExclusivo()) {
                nuevoJuego.agregarDescuento();
            }
            listaJuegos.add(nuevoJuego);
        }
        if (Datos_juegos.cbxPUBG.isSelected()) {
            nombre = "Player Unknown Battlegrounds";
            precio = 10;
            exclusividad = "No";
            Videojuego nuevoJuego = new Videojuego(nombre, precio, exclusividad);
            if (nuevoJuego.esExclusivo()) {
                nuevoJuego.agregarDescuento();
            }
            listaJuegos.add(nuevoJuego);
        }
        if (Datos_juegos.cbxPokemon.isSelected()) {
            nombre = "Pokémon: Espada y Escudo";
            precio = 100;
            exclusividad = "Si";
            Videojuego nuevoJuego = new VideojuegoNintendoSwitch(nombre, precio, exclusividad);
            if (nuevoJuego.esExclusivo()) {
                nuevoJuego.agregarDescuento();
            }
            listaJuegos.add(nuevoJuego);
        }
        if (Datos_juegos.cbxQuantumBreak.isSelected()) {
            nombre = "Quantum Break";
            precio = 26;
            exclusividad = "Sí";
            Videojuego nuevoJuego = new VideojuegoXboxOne(nombre, precio, exclusividad);
            if (nuevoJuego.esExclusivo()) {
                nuevoJuego.agregarDescuento();
            }
            listaJuegos.add(nuevoJuego);
        }
        if (Datos_juegos.cbxSeaOfTheThieves.isSelected()) {
            nombre = "Sea of Thieves";
            precio = 29;
            exclusividad = "Si";
            Videojuego nuevoJuego = new VideojuegoXboxOne(nombre, precio, exclusividad);
            if (nuevoJuego.esExclusivo()) {
                nuevoJuego.agregarDescuento();
            }
            listaJuegos.add(nuevoJuego);
        }
        if (Datos_juegos.cbxSuperMarioOdyssey.isSelected()) {
            nombre = "Super Mario Odyssey";
            precio = 50;
            exclusividad = "Si";
            Videojuego nuevoJuego = new VideojuegoNintendoSwitch(nombre, precio, exclusividad);
            if (nuevoJuego.esExclusivo()) {
                nuevoJuego.agregarDescuento();
            }
            listaJuegos.add(nuevoJuego);
        }
        if (Datos_juegos.cbxSuperSmashBrosUltimate.isSelected()) {
            nombre = "Super Smash Bros Ultimate";
            precio = 50;
            exclusividad = "Si";
            Videojuego nuevoJuego = new VideojuegoNintendoSwitch(nombre, precio, exclusividad);
            if (nuevoJuego.esExclusivo()) {
                nuevoJuego.agregarDescuento();
            }
            listaJuegos.add(nuevoJuego);
        }
        if (Datos_juegos.cbxTLOU2.isSelected()) {
            nombre = "The Last of Us Part 2";
            precio = 48;
            exclusividad = "Si";
            Videojuego nuevoJuego = new VideojuegoPS4(nombre, precio, exclusividad);
            if (nuevoJuego.esExclusivo()) {
                nuevoJuego.agregarDescuento();
            }
            listaJuegos.add(nuevoJuego);
        }
        if (Datos_juegos.cbxZeldaBW.isSelected()) {
            nombre = "The Legend of Zelda: Breath of the Wild";
            precio = 40;
            exclusividad = "Si";
            Videojuego nuevoJuego = new VideojuegoNintendoSwitch(nombre, precio, exclusividad);
            if (nuevoJuego.esExclusivo()) {
                nuevoJuego.agregarDescuento();
            }
            listaJuegos.add(nuevoJuego);
        }
        if (Datos_juegos.cbxZeldaLA.isSelected()) {
            nombre = "The Legend of Zelda: Link's Awakening";
            precio = 40;
            exclusividad = "Si";
            Videojuego nuevoJuego = new VideojuegoNintendoSwitch(nombre, precio, exclusividad);
            if (nuevoJuego.esExclusivo()) {
                nuevoJuego.agregarDescuento();
            }
            listaJuegos.add(nuevoJuego);
        }
        if (Datos_juegos.cbxRainbowSixSiege.isSelected()) {
            nombre = "Tom Clancy's Rainbow Six Siege";
            precio = 15;
            exclusividad = "No";
            Videojuego nuevoJuego = new Videojuego(nombre, precio, exclusividad);
            if (nuevoJuego.esExclusivo()) {
                nuevoJuego.agregarDescuento();
            }
            listaJuegos.add(nuevoJuego);
        }
        if (Datos_juegos.cbxUntilDawn.isSelected()) {
            nombre = "Until Dawn";
            precio = 26;
            exclusividad = "Si";
            Videojuego nuevoJuego = new VideojuegoPS4(nombre, precio, exclusividad);
            if (nuevoJuego.esExclusivo()) {
                nuevoJuego.agregarDescuento();
            }
            listaJuegos.add(nuevoJuego);
        }
        if (Datos_juegos.cbxWatchDogsLegion.isSelected()) {
            nombre = "Watch Dogs: Legion";
            precio = 70;
            exclusividad = "No";
            Videojuego nuevoJuego = new Videojuego(nombre, precio, exclusividad);
            if (nuevoJuego.esExclusivo()) {
                nuevoJuego.agregarDescuento();
            }
            listaJuegos.add(nuevoJuego);
        }
        if (Datos_juegos.cbxXenobladeChronicles.isSelected()) {
            nombre = "Xenoblade Chronicles: Definitive Edition";
            precio = 45;
            exclusividad = "Si";
            Videojuego nuevoJuego = new VideojuegoNintendoSwitch(nombre, precio, exclusividad);
            if (nuevoJuego.esExclusivo()) {
                nuevoJuego.agregarDescuento();
            }
            listaJuegos.add(nuevoJuego);
        }
        if(cbxInjustice2.isSelected()){
            nombre = "Injustice 2";
            precio = 17;
            exclusividad = "No";
            Videojuego nuevoJuego = new Videojuego(nombre,precio,exclusividad);
            if(nuevoJuego.esExclusivo()){
                nuevoJuego.agregarDescuento();
            }
            listaJuegos.add(nuevoJuego);
        }
        if(cbxRedDeadRedemption2.isSelected()){
            nombre = "Red Dead Redemption 2";
            precio = 49;
            exclusividad = "No";
            Videojuego nuevoJuego = new Videojuego(nombre,precio,exclusividad);
            if(nuevoJuego.esExclusivo()){
                nuevoJuego.agregarDescuento();
            }
            listaJuegos.add(nuevoJuego);
        }
        if(cbxRiseTombRaider.isSelected()){
            nombre = "Rise of the Tomb Raider";
            precio = 20;
            exclusividad = "No";
            Videojuego nuevoJuego = new Videojuego(nombre,precio,exclusividad);
            if(nuevoJuego.esExclusivo()){
                nuevoJuego.agregarDescuento();
            }
            listaJuegos.add(nuevoJuego);
        }
        
        
        double precioTotalJuegos = 0;
        double precioTotal=0;

        for (Videojuego objeto : listaJuegos) {
            precioTotalJuegos += objeto.getPrecio();
        }
        if (Gestion_Consolas.rbtNintendoSwitch.isSelected()) {
            txtConsolaAdquirida.setText(Gestion_Consolas.rbtNintendoSwitch.getText());
            txtPrecioConsola.setText((String) Gestion_Consolas.cmbPrecio.getSelectedItem());
            precioTotal= precioTotalJuegos + Double.valueOf(txtPrecioConsola.getText());
        }
        if (Gestion_Consolas.rbtPS4.isSelected()) {
            txtConsolaAdquirida.setText(Gestion_Consolas.rbtPS4.getText());
            txtPrecioConsola.setText((String) Gestion_Consolas.cmbPrecio.getSelectedItem());
             precioTotal= precioTotalJuegos + Double.valueOf(txtPrecioConsola.getText());
        }
        if (Gestion_Consolas.rbtXboxOne.isSelected()) {
            txtConsolaAdquirida.setText(Gestion_Consolas.rbtXboxOne.getText());
            txtPrecioConsola.setText((String) Gestion_Consolas.cmbPrecio.getSelectedItem());
            precioTotal= precioTotalJuegos + Double.valueOf(txtPrecioConsola.getText());
        }
        if (Gestion_Consolas.rbtNingunaConsola.isSelected()) {
            txtConsolaAdquirida.setEditable(false);
            txtPrecioConsola.setEditable(false);
            precioTotal= precioTotalJuegos + 0;
        }
        
        txtValorAPagar.setText(String.valueOf(precioTotal));
        
        if(listaJuegos.size()<5){
            cbmTipoComplemento.setEnabled(false);            
        } 
}

    }//GEN-LAST:event_txtApellidoKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Datos_del_Comprador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Datos_del_Comprador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Datos_del_Comprador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Datos_del_Comprador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Datos_del_Comprador().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGuardar;
    private javax.swing.JComboBox<String> cbmTipoComplemento;
    private javax.swing.JComboBox<String> cmbAño;
    private javax.swing.JComboBox<String> cmbDia;
    private javax.swing.JComboBox<String> cmbMes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblApellidp;
    private javax.swing.JLabel lblComplemento;
    private javax.swing.JLabel lblFecha;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblNumCedula;
    private javax.swing.JLabel lblNumFactura;
    private javax.swing.JLabel lblNumeral;
    private javax.swing.JLabel lblTexto;
    private javax.swing.JLabel lblTipoConsola;
    private javax.swing.JLabel lblValorAPagar;
    private javax.swing.JTextArea txaResultados;
    private javax.swing.JTextField txtApellido;
    private javax.swing.JTextField txtConsolaAdquirida;
    private javax.swing.JTextField txtCédula;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtPrecioConsola;
    private javax.swing.JTextField txtValorAPagar;
    // End of variables declaration//GEN-END:variables
}
