/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyecto_poo_;

/**
 *
 * @author Pavilion
 */
public class Gestion_Consolas extends javax.swing.JFrame {
    Consola nuevaConsola = new Consola();
    String compañiaDeFabricacion = "";
    String complemento = "Ninguno";
    double precio;

    /**
     * Creates new form Gestion_Consolas
     */
    public Gestion_Consolas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btgDatosConsola = new javax.swing.ButtonGroup();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblDato = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        rbtPS4 = new javax.swing.JRadioButton();
        rbtXboxOne = new javax.swing.JRadioButton();
        rbtNintendoSwitch = new javax.swing.JRadioButton();
        cmbPrecio = new javax.swing.JComboBox<>();
        btnSiguiente = new javax.swing.JButton();
        rbtNingunaConsola = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(255, 204, 204));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/ArrayGames.png"))); // NOI18N

        lblDato.setText("CONSOLAS");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Escoja la consola que desee comprar"));

        btgDatosConsola.add(rbtPS4);
        rbtPS4.setText("PS4");
        rbtPS4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtPS4ActionPerformed(evt);
            }
        });

        btgDatosConsola.add(rbtXboxOne);
        rbtXboxOne.setText("XBox One");
        rbtXboxOne.setToolTipText("");
        rbtXboxOne.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtXboxOneActionPerformed(evt);
            }
        });

        btgDatosConsola.add(rbtNintendoSwitch);
        rbtNintendoSwitch.setText("Nintento Switch");
        rbtNintendoSwitch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtNintendoSwitchActionPerformed(evt);
            }
        });

        cmbPrecio.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Precio", "250", "280", "300", "330", "380", "410", "450" }));

        btnSiguiente.setText("Catálogo de videojuegos >");
        btnSiguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSiguienteActionPerformed(evt);
            }
        });

        btgDatosConsola.add(rbtNingunaConsola);
        rbtNingunaConsola.setText("No estoy interesado en comprar una consola");
        rbtNingunaConsola.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtNingunaConsolaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rbtNingunaConsola)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(145, 145, 145)
                                .addComponent(btnSiguiente)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rbtPS4)
                            .addComponent(rbtNintendoSwitch))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(rbtXboxOne)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cmbPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(49, 49, 49))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(rbtPS4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbtXboxOne)
                    .addComponent(cmbPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rbtNintendoSwitch)
                .addGap(18, 18, 18)
                .addComponent(rbtNingunaConsola)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSiguiente)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(95, 95, 95)
                        .addComponent(lblDato))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(69, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(28, 28, 28))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(lblDato)
                        .addGap(18, 18, 18)))
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSiguienteActionPerformed
        // TODO add your handling code here:
        Datos_juegos abrir = new Datos_juegos();
        abrir.setVisible(true);
        this.setVisible(false);
        if(rbtNingunaConsola.isSelected()){
            nuevaConsola = nuevaConsola;
        }
        if(rbtPS4.isSelected()){
            compañiaDeFabricacion = "Sony";
        }else if(rbtXboxOne.isSelected()){
            compañiaDeFabricacion = "Microsoft";
        }else if(rbtNintendoSwitch.isSelected()){
            compañiaDeFabricacion = "Nintendo";
        }
        precio = (Double) cmbPrecio.getSelectedItem();
        nuevaConsola.setCompañiaDeFabricacion(compañiaDeFabricacion);
        nuevaConsola.setComplemento(complemento);
        nuevaConsola.setPrecio(precio);
    }//GEN-LAST:event_btnSiguienteActionPerformed

    private void rbtNingunaConsolaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtNingunaConsolaActionPerformed
        // TODO add your handling code here:
        
            cmbPrecio.setEnabled(false);
        
        
    }//GEN-LAST:event_rbtNingunaConsolaActionPerformed

    private void rbtNintendoSwitchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtNintendoSwitchActionPerformed
        // TODO add your handling code here:
        cmbPrecio.setEnabled(true);
    }//GEN-LAST:event_rbtNintendoSwitchActionPerformed

    private void rbtXboxOneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtXboxOneActionPerformed
        // TODO add your handling code here:
        cmbPrecio.setEnabled(true);
    }//GEN-LAST:event_rbtXboxOneActionPerformed

    private void rbtPS4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtPS4ActionPerformed
        // TODO add your handling code here:
        cmbPrecio.setEnabled(true);
    }//GEN-LAST:event_rbtPS4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Gestion_Consolas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Gestion_Consolas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Gestion_Consolas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Gestion_Consolas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Gestion_Consolas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup btgDatosConsola;
    private javax.swing.JButton btnSiguiente;
    protected static javax.swing.JComboBox<String> cmbPrecio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblDato;
    protected static javax.swing.JRadioButton rbtNingunaConsola;
    protected static javax.swing.JRadioButton rbtNintendoSwitch;
    protected static javax.swing.JRadioButton rbtPS4;
    protected static javax.swing.JRadioButton rbtXboxOne;
    // End of variables declaration//GEN-END:variables
}
